name: conveyor
description: Conveyor
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  clock: ^1.1.1
  meta: ^1.11.0

dev_dependencies:
  collection: ^1.19.0
  fake_async: ^1.3.1
  lints: ^3.0.0
  test: ^1.24.0
